import type { ThemeConfig, Cryptid } from '../../../types';

export const cryptidTheme: ThemeConfig = {
  id: 'cryptids',
  name: 'Cryptid Hunt',
  colors: {
    primary: '#2d5016',
    secondary: '#4a7c23',
    accent: '#d4a843',
    background: '#f5f0e1',
    surface: '#ffffff',
    text: '#3d2b1f',
    textLight: '#6b5a4e',
    success: '#4a7c23',
    error: '#c0392b',
    warning: '#d4a843',
  },
  narrativeTemplates: {
    welcome: "Welcome back, Investigator! Your field journal awaits.",
    session_start: "New evidence has been reported. Let's investigate!",
    correct_answer: "Excellent fieldwork! You're one step closer to the truth.",
    wrong_answer: "Hmm, that trail went cold. Let's try another approach.",
    streak_3: "You're on a hot trail! Keep going!",
    streak_5: "Incredible tracking skills! The creature can't hide from you!",
    streak_10: "LEGENDARY investigator status! Nothing escapes your eye!",
    evidence_found: "You found a piece of evidence! Add it to your field journal.",
    cryptid_unlocked: "A new cryptid location has been revealed on your map!",
    cryptid_discovered: "AMAZING DISCOVERY! You've identified a new cryptid!",
    frustration_pivot: "The trail went cold here... let's check another lead!",
    daily_login: "Your daily field supply has arrived! Ready to investigate?",
    subject_math: "Solve this to decode the cryptid's coordinates!",
    subject_ela: "Read this eyewitness report carefully for clues!",
    subject_science: "Use your scientist skills to analyze this evidence!",
    subject_social_studies: "Check your field maps and historical records!",
  },
  milestoneMessages: {
    first_evidence: "Your first piece of evidence! The hunt begins!",
    five_evidence: "Five clues collected — you're a natural investigator!",
    first_cryptid: "You've discovered your first cryptid! Check your Field Guide!",
    all_cryptids: "You've found ALL the cryptids! You're a Master Investigator!",
    level_5: "Level 5! You've earned your Junior Investigator badge!",
    level_10: "Level 10! Senior Investigator status unlocked!",
    streak_10: "10 in a row! Your tracking instincts are legendary!",
  },
};

export const cryptidRoster: Cryptid[] = [
  {
    id: 'honey-island-swamp-monster',
    name: 'Honey Island Swamp Monster',
    description: 'A mysterious creature lurking in the swamps of Louisiana. Locals say it smells like rotten eggs!',
    region: 'Louisiana Bayou',
    difficulty: 1,
    svgSilhouette: '/assets/cryptids/honey-island-swamp-monster.svg',
    clues: [
      { id: 'hism-1', type: 'footprint', description: 'Three-toed footprint in the mud', svgIcon: '/assets/ui/clue-footprint.svg', revealed: false },
      { id: 'hism-2', type: 'witness', description: 'A fisherman saw something large moving through the reeds', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'hism-3', type: 'sample', description: 'Strange green slime on a cypress tree', svgIcon: '/assets/ui/clue-sample.svg', revealed: false },
      { id: 'hism-4', type: 'sketch', description: 'A blurry sketch from a trail camera', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'hism-5', type: 'map_pin', description: 'Multiple sightings near Pearl River', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
    ],
    cardStats: { danger: 3, stealth: 5, mystery: 4 },
  },
  {
    id: 'rougarou',
    name: 'Rougarou',
    description: 'A werewolf-like beast from Cajun legend that prowls the sugar cane fields at night.',
    region: 'Cajun Country',
    difficulty: 2,
    svgSilhouette: '/assets/cryptids/rougarou.svg',
    clues: [
      { id: 'rou-1', type: 'footprint', description: 'Wolf-like tracks that suddenly turn into human footprints', svgIcon: '/assets/ui/clue-footprint.svg', revealed: false },
      { id: 'rou-2', type: 'witness', description: 'A farmer heard howling during a full moon', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'rou-3', type: 'sketch', description: 'Torn fabric caught on a sugar cane stalk', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'rou-4', type: 'photo', description: 'A shadowy figure in a nighttime trail photo', svgIcon: '/assets/ui/clue-photo.svg', revealed: false },
      { id: 'rou-5', type: 'map_pin', description: 'Sightings cluster around Atchafalaya Basin', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
    ],
    cardStats: { danger: 5, stealth: 4, mystery: 3 },
  },
  {
    id: 'bigfoot',
    name: 'Bigfoot',
    description: 'The legendary ape-like creature spotted in forests across North America.',
    region: 'Pacific Northwest',
    difficulty: 3,
    svgSilhouette: '/assets/cryptids/bigfoot.svg',
    clues: [
      { id: 'bf-1', type: 'footprint', description: 'Enormous footprint — 16 inches long!', svgIcon: '/assets/ui/clue-footprint.svg', revealed: false },
      { id: 'bf-2', type: 'witness', description: 'A hiker reported seeing a tall, hairy figure', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'bf-3', type: 'sample', description: 'Tufts of coarse brown hair on a branch', svgIcon: '/assets/ui/clue-sample.svg', revealed: false },
      { id: 'bf-4', type: 'sketch', description: 'The famous Patterson-Gimlin film still', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'bf-5', type: 'map_pin', description: 'Reports from Bluff Creek, California', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
      { id: 'bf-6', type: 'witness', description: 'Wood knocking sounds heard at night', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
    ],
    cardStats: { danger: 3, stealth: 4, mystery: 5 },
  },
  {
    id: 'mothman',
    name: 'Mothman',
    description: 'A winged creature with glowing red eyes, first spotted in West Virginia.',
    region: 'Point Pleasant, WV',
    difficulty: 4,
    svgSilhouette: '/assets/cryptids/mothman.svg',
    clues: [
      { id: 'mm-1', type: 'witness', description: 'Two couples saw glowing red eyes near an old factory', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'mm-2', type: 'sketch', description: 'Drawing of a man-sized creature with 10-foot wingspan', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'mm-3', type: 'map_pin', description: 'All sightings near the TNT area', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
      { id: 'mm-4', type: 'photo', description: 'Strange shadow on a security camera', svgIcon: '/assets/ui/clue-photo.svg', revealed: false },
      { id: 'mm-5', type: 'witness', description: 'Car chased by flying creature at 100 mph', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
    ],
    cardStats: { danger: 4, stealth: 3, mystery: 5 },
  },
  {
    id: 'chupacabra',
    name: 'Chupacabra',
    description: 'The "goat sucker" — a spiny creature reported across the Americas.',
    region: 'Puerto Rico & Texas',
    difficulty: 5,
    svgSilhouette: '/assets/cryptids/chupacabra.svg',
    clues: [
      { id: 'ch-1', type: 'footprint', description: 'Small clawed tracks near a farm', svgIcon: '/assets/ui/clue-footprint.svg', revealed: false },
      { id: 'ch-2', type: 'witness', description: 'A farmer found strange marks on livestock', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'ch-3', type: 'sample', description: 'Unusual quill-like spines found in a field', svgIcon: '/assets/ui/clue-sample.svg', revealed: false },
      { id: 'ch-4', type: 'sketch', description: 'A child drew what they saw in the moonlight', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'ch-5', type: 'map_pin', description: 'Reports span from Puerto Rico to Texas', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
    ],
    cardStats: { danger: 4, stealth: 5, mystery: 4 },
  },
  {
    id: 'jersey-devil',
    name: 'Jersey Devil',
    description: 'A flying creature with hooves and a forked tail from the Pine Barrens of New Jersey.',
    region: 'Pine Barrens, NJ',
    difficulty: 6,
    svgSilhouette: '/assets/cryptids/jersey-devil.svg',
    clues: [
      { id: 'jd-1', type: 'footprint', description: 'Hoof prints on a rooftop — how did it get up there?', svgIcon: '/assets/ui/clue-footprint.svg', revealed: false },
      { id: 'jd-2', type: 'witness', description: 'A police officer reported a screaming, winged creature', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'jd-3', type: 'sketch', description: 'Historical sketch from 1909 newspaper', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'jd-4', type: 'map_pin', description: 'Centered in Burlington County, NJ', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
      { id: 'jd-5', type: 'photo', description: 'Strange shadow against the full moon', svgIcon: '/assets/ui/clue-photo.svg', revealed: false },
    ],
    cardStats: { danger: 3, stealth: 4, mystery: 5 },
  },
  {
    id: 'thunderbird',
    name: 'Thunderbird',
    description: 'A massive bird from Native American legend with a wingspan wider than an airplane.',
    region: 'Great Plains',
    difficulty: 7,
    svgSilhouette: '/assets/cryptids/thunderbird.svg',
    clues: [
      { id: 'tb-1', type: 'witness', description: 'A pilot saw a bird larger than his small plane', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'tb-2', type: 'sketch', description: 'Ancient cave painting of a giant bird', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'tb-3', type: 'sample', description: 'A feather longer than your arm', svgIcon: '/assets/ui/clue-sample.svg', revealed: false },
      { id: 'tb-4', type: 'map_pin', description: 'Sightings along the Rocky Mountains', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
      { id: 'tb-5', type: 'photo', description: 'Enormous shadow captured by a weather satellite', svgIcon: '/assets/ui/clue-photo.svg', revealed: false },
    ],
    cardStats: { danger: 5, stealth: 2, mystery: 5 },
  },
  {
    id: 'loch-ness-monster',
    name: 'Loch Ness Monster',
    description: 'Nessie — the legendary lake creature of Scotland. Could it be a surviving dinosaur?',
    region: 'Loch Ness, Scotland',
    difficulty: 8,
    svgSilhouette: '/assets/cryptids/loch-ness-monster.svg',
    clues: [
      { id: 'ln-1', type: 'photo', description: 'The famous "Surgeon\'s Photo" — real or fake?', svgIcon: '/assets/ui/clue-photo.svg', revealed: false },
      { id: 'ln-2', type: 'witness', description: 'A boat captain saw humps moving through the water', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
      { id: 'ln-3', type: 'sample', description: 'Unusual sonar readings from the lake bottom', svgIcon: '/assets/ui/clue-sample.svg', revealed: false },
      { id: 'ln-4', type: 'sketch', description: 'A drawing from a Scottish monk in the year 565', svgIcon: '/assets/ui/clue-sketch.svg', revealed: false },
      { id: 'ln-5', type: 'map_pin', description: 'Sightings cluster near Urquhart Castle', svgIcon: '/assets/ui/clue-map-pin.svg', revealed: false },
      { id: 'ln-6', type: 'witness', description: 'Ripples in perfectly calm water', svgIcon: '/assets/ui/clue-witness.svg', revealed: false },
    ],
    cardStats: { danger: 2, stealth: 5, mystery: 5 },
  },
];
